//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\VDMY\source\repos\cppCodeRules\AntlrCSharp\CPP14Parser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CPP14Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ICPP14ParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.translationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTranslationUnit([NotNull] CPP14Parser.TranslationUnitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpression([NotNull] CPP14Parser.PrimaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.idExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdExpression([NotNull] CPP14Parser.IdExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.unqualifiedId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnqualifiedId([NotNull] CPP14Parser.UnqualifiedIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.qualifiedId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedId([NotNull] CPP14Parser.QualifiedIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.nestedNameSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNestedNameSpecifier([NotNull] CPP14Parser.NestedNameSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.lambdaExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaExpression([NotNull] CPP14Parser.LambdaExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.lambdaIntroducer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaIntroducer([NotNull] CPP14Parser.LambdaIntroducerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.lambdaCapture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaCapture([NotNull] CPP14Parser.LambdaCaptureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.captureDefault"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaptureDefault([NotNull] CPP14Parser.CaptureDefaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.captureList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaptureList([NotNull] CPP14Parser.CaptureListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.capture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCapture([NotNull] CPP14Parser.CaptureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.simpleCapture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleCapture([NotNull] CPP14Parser.SimpleCaptureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.initcapture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitcapture([NotNull] CPP14Parser.InitcaptureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.lambdaDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaDeclarator([NotNull] CPP14Parser.LambdaDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfixExpression([NotNull] CPP14Parser.PostfixExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.typeIdOfTheTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeIdOfTheTypeId([NotNull] CPP14Parser.TypeIdOfTheTypeIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionList([NotNull] CPP14Parser.ExpressionListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.pseudoDestructorName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPseudoDestructorName([NotNull] CPP14Parser.PseudoDestructorNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpression([NotNull] CPP14Parser.UnaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryOperator([NotNull] CPP14Parser.UnaryOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.newExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewExpression([NotNull] CPP14Parser.NewExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.newPlacement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewPlacement([NotNull] CPP14Parser.NewPlacementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.newTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewTypeId([NotNull] CPP14Parser.NewTypeIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.newDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewDeclarator([NotNull] CPP14Parser.NewDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.noPointerNewDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoPointerNewDeclarator([NotNull] CPP14Parser.NoPointerNewDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.newInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewInitializer([NotNull] CPP14Parser.NewInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.deleteExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeleteExpression([NotNull] CPP14Parser.DeleteExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.noExceptExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoExceptExpression([NotNull] CPP14Parser.NoExceptExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.castExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCastExpression([NotNull] CPP14Parser.CastExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.pointerMemberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointerMemberExpression([NotNull] CPP14Parser.PointerMemberExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpression([NotNull] CPP14Parser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpression([NotNull] CPP14Parser.AdditiveExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.shiftExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShiftExpression([NotNull] CPP14Parser.ShiftExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.shiftOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShiftOperator([NotNull] CPP14Parser.ShiftOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpression([NotNull] CPP14Parser.RelationalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualityExpression([NotNull] CPP14Parser.EqualityExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpression([NotNull] CPP14Parser.AndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.exclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExclusiveOrExpression([NotNull] CPP14Parser.ExclusiveOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.inclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInclusiveOrExpression([NotNull] CPP14Parser.InclusiveOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalAndExpression([NotNull] CPP14Parser.LogicalAndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOrExpression([NotNull] CPP14Parser.LogicalOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionalExpression([NotNull] CPP14Parser.ConditionalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentExpression([NotNull] CPP14Parser.AssignmentExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentOperator([NotNull] CPP14Parser.AssignmentOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] CPP14Parser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.constantExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantExpression([NotNull] CPP14Parser.ConstantExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] CPP14Parser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.labeledStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabeledStatement([NotNull] CPP14Parser.LabeledStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] CPP14Parser.ExpressionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.compoundStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompoundStatement([NotNull] CPP14Parser.CompoundStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.statementSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementSeq([NotNull] CPP14Parser.StatementSeqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.selectionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectionStatement([NotNull] CPP14Parser.SelectionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] CPP14Parser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.iterationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIterationStatement([NotNull] CPP14Parser.IterationStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.forInitStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForInitStatement([NotNull] CPP14Parser.ForInitStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.forRangeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForRangeDeclaration([NotNull] CPP14Parser.ForRangeDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.forRangeInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForRangeInitializer([NotNull] CPP14Parser.ForRangeInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJumpStatement([NotNull] CPP14Parser.JumpStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationStatement([NotNull] CPP14Parser.DeclarationStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.declarationseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationseq([NotNull] CPP14Parser.DeclarationseqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] CPP14Parser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.blockDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockDeclaration([NotNull] CPP14Parser.BlockDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.aliasDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAliasDeclaration([NotNull] CPP14Parser.AliasDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.simpleDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleDeclaration([NotNull] CPP14Parser.SimpleDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.staticAssertDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStaticAssertDeclaration([NotNull] CPP14Parser.StaticAssertDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.emptyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyDeclaration([NotNull] CPP14Parser.EmptyDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.attributeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeDeclaration([NotNull] CPP14Parser.AttributeDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.declSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclSpecifier([NotNull] CPP14Parser.DeclSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.declSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclSpecifierSeq([NotNull] CPP14Parser.DeclSpecifierSeqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.storageClassSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStorageClassSpecifier([NotNull] CPP14Parser.StorageClassSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.functionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionSpecifier([NotNull] CPP14Parser.FunctionSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.typedefName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypedefName([NotNull] CPP14Parser.TypedefNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeSpecifier([NotNull] CPP14Parser.TypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.trailingTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrailingTypeSpecifier([NotNull] CPP14Parser.TrailingTypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.typeSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeSpecifierSeq([NotNull] CPP14Parser.TypeSpecifierSeqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.trailingTypeSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrailingTypeSpecifierSeq([NotNull] CPP14Parser.TrailingTypeSpecifierSeqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.simpleTypeLengthModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleTypeLengthModifier([NotNull] CPP14Parser.SimpleTypeLengthModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.simpleTypeSignednessModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleTypeSignednessModifier([NotNull] CPP14Parser.SimpleTypeSignednessModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.simpleTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleTypeSpecifier([NotNull] CPP14Parser.SimpleTypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.theTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTheTypeName([NotNull] CPP14Parser.TheTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.decltypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecltypeSpecifier([NotNull] CPP14Parser.DecltypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.elaboratedTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElaboratedTypeSpecifier([NotNull] CPP14Parser.ElaboratedTypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.enumName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumName([NotNull] CPP14Parser.EnumNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.enumSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumSpecifier([NotNull] CPP14Parser.EnumSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.enumHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumHead([NotNull] CPP14Parser.EnumHeadContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.opaqueEnumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpaqueEnumDeclaration([NotNull] CPP14Parser.OpaqueEnumDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.enumkey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumkey([NotNull] CPP14Parser.EnumkeyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.enumbase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumbase([NotNull] CPP14Parser.EnumbaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.enumeratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumeratorList([NotNull] CPP14Parser.EnumeratorListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.enumeratorDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumeratorDefinition([NotNull] CPP14Parser.EnumeratorDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.enumerator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerator([NotNull] CPP14Parser.EnumeratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.namespaceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceName([NotNull] CPP14Parser.NamespaceNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.originalNamespaceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOriginalNamespaceName([NotNull] CPP14Parser.OriginalNamespaceNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.namespaceDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceDefinition([NotNull] CPP14Parser.NamespaceDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.namespaceAlias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceAlias([NotNull] CPP14Parser.NamespaceAliasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.namespaceAliasDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceAliasDefinition([NotNull] CPP14Parser.NamespaceAliasDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.qualifiednamespacespecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiednamespacespecifier([NotNull] CPP14Parser.QualifiednamespacespecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.usingDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsingDeclaration([NotNull] CPP14Parser.UsingDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.usingDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsingDirective([NotNull] CPP14Parser.UsingDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.asmDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsmDefinition([NotNull] CPP14Parser.AsmDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.linkageSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLinkageSpecification([NotNull] CPP14Parser.LinkageSpecificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.attributeSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeSpecifierSeq([NotNull] CPP14Parser.AttributeSpecifierSeqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.attributeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeSpecifier([NotNull] CPP14Parser.AttributeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.alignmentspecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlignmentspecifier([NotNull] CPP14Parser.AlignmentspecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.attributeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeList([NotNull] CPP14Parser.AttributeListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] CPP14Parser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.attributeNamespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeNamespace([NotNull] CPP14Parser.AttributeNamespaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.attributeArgumentClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeArgumentClause([NotNull] CPP14Parser.AttributeArgumentClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.balancedTokenSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBalancedTokenSeq([NotNull] CPP14Parser.BalancedTokenSeqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.balancedtoken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBalancedtoken([NotNull] CPP14Parser.BalancedtokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.initDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitDeclaratorList([NotNull] CPP14Parser.InitDeclaratorListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.initDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitDeclarator([NotNull] CPP14Parser.InitDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarator([NotNull] CPP14Parser.DeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.pointerDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointerDeclarator([NotNull] CPP14Parser.PointerDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.noPointerDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoPointerDeclarator([NotNull] CPP14Parser.NoPointerDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.parametersAndQualifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParametersAndQualifiers([NotNull] CPP14Parser.ParametersAndQualifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.trailingReturnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrailingReturnType([NotNull] CPP14Parser.TrailingReturnTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.pointerOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointerOperator([NotNull] CPP14Parser.PointerOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.cvqualifierseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCvqualifierseq([NotNull] CPP14Parser.CvqualifierseqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.cvQualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCvQualifier([NotNull] CPP14Parser.CvQualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.refqualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRefqualifier([NotNull] CPP14Parser.RefqualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.declaratorid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaratorid([NotNull] CPP14Parser.DeclaratoridContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.theTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTheTypeId([NotNull] CPP14Parser.TheTypeIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.abstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbstractDeclarator([NotNull] CPP14Parser.AbstractDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.pointerAbstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointerAbstractDeclarator([NotNull] CPP14Parser.PointerAbstractDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.noPointerAbstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoPointerAbstractDeclarator([NotNull] CPP14Parser.NoPointerAbstractDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.abstractPackDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbstractPackDeclarator([NotNull] CPP14Parser.AbstractPackDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.noPointerAbstractPackDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoPointerAbstractPackDeclarator([NotNull] CPP14Parser.NoPointerAbstractPackDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.parameterDeclarationClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterDeclarationClause([NotNull] CPP14Parser.ParameterDeclarationClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.parameterDeclarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterDeclarationList([NotNull] CPP14Parser.ParameterDeclarationListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.parameterDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterDeclaration([NotNull] CPP14Parser.ParameterDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDefinition([NotNull] CPP14Parser.FunctionDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.functionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionBody([NotNull] CPP14Parser.FunctionBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializer([NotNull] CPP14Parser.InitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.braceOrEqualInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBraceOrEqualInitializer([NotNull] CPP14Parser.BraceOrEqualInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.initializerClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializerClause([NotNull] CPP14Parser.InitializerClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.initializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializerList([NotNull] CPP14Parser.InitializerListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.bracedInitList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracedInitList([NotNull] CPP14Parser.BracedInitListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassName([NotNull] CPP14Parser.ClassNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.classSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassSpecifier([NotNull] CPP14Parser.ClassSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.classHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassHead([NotNull] CPP14Parser.ClassHeadContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.classHeadName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassHeadName([NotNull] CPP14Parser.ClassHeadNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.classVirtSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassVirtSpecifier([NotNull] CPP14Parser.ClassVirtSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.classKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassKey([NotNull] CPP14Parser.ClassKeyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.memberSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberSpecification([NotNull] CPP14Parser.MemberSpecificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.memberdeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberdeclaration([NotNull] CPP14Parser.MemberdeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.memberDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberDeclaratorList([NotNull] CPP14Parser.MemberDeclaratorListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.memberDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberDeclarator([NotNull] CPP14Parser.MemberDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.virtualSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVirtualSpecifierSeq([NotNull] CPP14Parser.VirtualSpecifierSeqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.virtualSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVirtualSpecifier([NotNull] CPP14Parser.VirtualSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.pureSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPureSpecifier([NotNull] CPP14Parser.PureSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.baseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseClause([NotNull] CPP14Parser.BaseClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.baseSpecifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseSpecifierList([NotNull] CPP14Parser.BaseSpecifierListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.baseSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseSpecifier([NotNull] CPP14Parser.BaseSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.classOrDeclType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassOrDeclType([NotNull] CPP14Parser.ClassOrDeclTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.baseTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseTypeSpecifier([NotNull] CPP14Parser.BaseTypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.accessSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessSpecifier([NotNull] CPP14Parser.AccessSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.conversionFunctionId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConversionFunctionId([NotNull] CPP14Parser.ConversionFunctionIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.conversionTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConversionTypeId([NotNull] CPP14Parser.ConversionTypeIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.conversionDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConversionDeclarator([NotNull] CPP14Parser.ConversionDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.constructorInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructorInitializer([NotNull] CPP14Parser.ConstructorInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.memInitializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemInitializerList([NotNull] CPP14Parser.MemInitializerListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.memInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemInitializer([NotNull] CPP14Parser.MemInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.meminitializerid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMeminitializerid([NotNull] CPP14Parser.MeminitializeridContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.operatorFunctionId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorFunctionId([NotNull] CPP14Parser.OperatorFunctionIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.literalOperatorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralOperatorId([NotNull] CPP14Parser.LiteralOperatorIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.templateDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateDeclaration([NotNull] CPP14Parser.TemplateDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.templateparameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateparameterList([NotNull] CPP14Parser.TemplateparameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.templateParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateParameter([NotNull] CPP14Parser.TemplateParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.typeParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParameter([NotNull] CPP14Parser.TypeParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.simpleTemplateId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleTemplateId([NotNull] CPP14Parser.SimpleTemplateIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.templateId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateId([NotNull] CPP14Parser.TemplateIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.templateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateName([NotNull] CPP14Parser.TemplateNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.templateArgumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateArgumentList([NotNull] CPP14Parser.TemplateArgumentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.templateArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateArgument([NotNull] CPP14Parser.TemplateArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.typeNameSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeNameSpecifier([NotNull] CPP14Parser.TypeNameSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.explicitInstantiation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicitInstantiation([NotNull] CPP14Parser.ExplicitInstantiationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.explicitSpecialization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicitSpecialization([NotNull] CPP14Parser.ExplicitSpecializationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.tryBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTryBlock([NotNull] CPP14Parser.TryBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.functionTryBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionTryBlock([NotNull] CPP14Parser.FunctionTryBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.handlerSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHandlerSeq([NotNull] CPP14Parser.HandlerSeqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.handler"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHandler([NotNull] CPP14Parser.HandlerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.exceptionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExceptionDeclaration([NotNull] CPP14Parser.ExceptionDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.throwExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThrowExpression([NotNull] CPP14Parser.ThrowExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.exceptionSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExceptionSpecification([NotNull] CPP14Parser.ExceptionSpecificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.dynamicExceptionSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDynamicExceptionSpecification([NotNull] CPP14Parser.DynamicExceptionSpecificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.typeIdList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeIdList([NotNull] CPP14Parser.TypeIdListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.noeExceptSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoeExceptSpecification([NotNull] CPP14Parser.NoeExceptSpecificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.theOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTheOperator([NotNull] CPP14Parser.TheOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPP14Parser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] CPP14Parser.LiteralContext context);
}
